// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: profile/Profile.proto
// </auto-generated>
// Original file comments:
//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SkyWalking.NetworkProtocol.V3 {
  public static partial class ProfileTask
  {
    static readonly string __ServiceName = "ProfileTask";

    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery> __Marshaller_ProfileTaskCommandQuery = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.V3.Commands> __Marshaller_Commands = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.V3.Commands.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot> __Marshaller_ThreadSnapshot = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport> __Marshaller_ProfileTaskFinishReport = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport.Parser.ParseFrom);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery, global::SkyWalking.NetworkProtocol.V3.Commands> __Method_getProfileTaskCommands = new grpc::Method<global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery, global::SkyWalking.NetworkProtocol.V3.Commands>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getProfileTaskCommands",
        __Marshaller_ProfileTaskCommandQuery,
        __Marshaller_Commands);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot, global::SkyWalking.NetworkProtocol.V3.Commands> __Method_collectSnapshot = new grpc::Method<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot, global::SkyWalking.NetworkProtocol.V3.Commands>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "collectSnapshot",
        __Marshaller_ThreadSnapshot,
        __Marshaller_Commands);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport, global::SkyWalking.NetworkProtocol.V3.Commands> __Method_reportTaskFinish = new grpc::Method<global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport, global::SkyWalking.NetworkProtocol.V3.Commands>(
        grpc::MethodType.Unary,
        __ServiceName,
        "reportTaskFinish",
        __Marshaller_ProfileTaskFinishReport,
        __Marshaller_Commands);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SkyWalking.NetworkProtocol.V3.ProfileReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProfileTask</summary>
    [grpc::BindServiceMethod(typeof(ProfileTask), "BindService")]
    public abstract partial class ProfileTaskBase
    {
      /// <summary>
      /// query all sniffer need to execute profile task commands
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.V3.Commands> getProfileTaskCommands(global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// collect dumped thread snapshot
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.V3.Commands> collectSnapshot(grpc::IAsyncStreamReader<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// report profiling task finished
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.V3.Commands> reportTaskFinish(global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProfileTask</summary>
    public partial class ProfileTaskClient : grpc::ClientBase<ProfileTaskClient>
    {
      /// <summary>Creates a new client for ProfileTask</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ProfileTaskClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProfileTask that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ProfileTaskClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ProfileTaskClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ProfileTaskClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// query all sniffer need to execute profile task commands
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::SkyWalking.NetworkProtocol.V3.Commands getProfileTaskCommands(global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getProfileTaskCommands(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// query all sniffer need to execute profile task commands
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::SkyWalking.NetworkProtocol.V3.Commands getProfileTaskCommands(global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getProfileTaskCommands, null, options, request);
      }
      /// <summary>
      /// query all sniffer need to execute profile task commands
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.V3.Commands> getProfileTaskCommandsAsync(global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getProfileTaskCommandsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// query all sniffer need to execute profile task commands
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.V3.Commands> getProfileTaskCommandsAsync(global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getProfileTaskCommands, null, options, request);
      }
      /// <summary>
      /// collect dumped thread snapshot
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot, global::SkyWalking.NetworkProtocol.V3.Commands> collectSnapshot(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return collectSnapshot(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// collect dumped thread snapshot
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot, global::SkyWalking.NetworkProtocol.V3.Commands> collectSnapshot(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_collectSnapshot, null, options);
      }
      /// <summary>
      /// report profiling task finished
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::SkyWalking.NetworkProtocol.V3.Commands reportTaskFinish(global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return reportTaskFinish(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// report profiling task finished
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::SkyWalking.NetworkProtocol.V3.Commands reportTaskFinish(global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_reportTaskFinish, null, options, request);
      }
      /// <summary>
      /// report profiling task finished
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.V3.Commands> reportTaskFinishAsync(global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return reportTaskFinishAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// report profiling task finished
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.V3.Commands> reportTaskFinishAsync(global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_reportTaskFinish, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ProfileTaskClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProfileTaskClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ProfileTaskBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_getProfileTaskCommands, serviceImpl.getProfileTaskCommands)
          .AddMethod(__Method_collectSnapshot, serviceImpl.collectSnapshot)
          .AddMethod(__Method_reportTaskFinish, serviceImpl.reportTaskFinish).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProfileTaskBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_getProfileTaskCommands, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SkyWalking.NetworkProtocol.V3.ProfileTaskCommandQuery, global::SkyWalking.NetworkProtocol.V3.Commands>(serviceImpl.getProfileTaskCommands));
      serviceBinder.AddMethod(__Method_collectSnapshot, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::SkyWalking.NetworkProtocol.V3.ThreadSnapshot, global::SkyWalking.NetworkProtocol.V3.Commands>(serviceImpl.collectSnapshot));
      serviceBinder.AddMethod(__Method_reportTaskFinish, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SkyWalking.NetworkProtocol.V3.ProfileTaskFinishReport, global::SkyWalking.NetworkProtocol.V3.Commands>(serviceImpl.reportTaskFinish));
    }

  }
}
#endregion
