// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service-mesh-probe/service-mesh.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkyWalking.NetworkProtocol.V3 {

  /// <summary>Holder for reflection information generated from service-mesh-probe/service-mesh.proto</summary>
  public static partial class ServiceMeshReflection {

    #region Descriptor
    /// <summary>File descriptor for service-mesh-probe/service-mesh.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceMeshReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVzZXJ2aWNlLW1lc2gtcHJvYmUvc2VydmljZS1tZXNoLnByb3RvGhNjb21t",
            "b24vQ29tbW9uLnByb3RvIrACChFTZXJ2aWNlTWVzaE1ldHJpYxIRCglzdGFy",
            "dFRpbWUYASABKAMSDwoHZW5kVGltZRgCIAEoAxIZChFzb3VyY2VTZXJ2aWNl",
            "TmFtZRgDIAEoCRIdChVzb3VyY2VTZXJ2aWNlSW5zdGFuY2UYBCABKAkSFwoP",
            "ZGVzdFNlcnZpY2VOYW1lGAUgASgJEhsKE2Rlc3RTZXJ2aWNlSW5zdGFuY2UY",
            "BiABKAkSEAoIZW5kcG9pbnQYByABKAkSDwoHbGF0ZW5jeRgIIAEoBRIUCgxy",
            "ZXNwb25zZUNvZGUYCSABKAUSDgoGc3RhdHVzGAogASgIEhsKCHByb3RvY29s",
            "GAsgASgOMgkuUHJvdG9jb2wSIQoLZGV0ZWN0UG9pbnQYDCABKA4yDC5EZXRl",
            "Y3RQb2ludCIVChNNZXNoUHJvYmVEb3duc3RyZWFtKh4KCFByb3RvY29sEggK",
            "BEhUVFAQABIICgRnUlBDEAEyUwoYU2VydmljZU1lc2hNZXRyaWNTZXJ2aWNl",
            "EjcKB2NvbGxlY3QSEi5TZXJ2aWNlTWVzaE1ldHJpYxoULk1lc2hQcm9iZURv",
            "d25zdHJlYW0iACgBQncKMG9yZy5hcGFjaGUuc2t5d2Fsa2luZy5hcG0ubmV0",
            "d29yay5zZXJ2aWNlbWVzaC52M1ABWiFza3l3YWxraW5nL25ldHdvcmsvc2Vy",
            "dmljZW1lc2gvdjOqAh1Ta3lXYWxraW5nLk5ldHdvcmtQcm90b2NvbC5WM2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkyWalking.NetworkProtocol.V3.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SkyWalking.NetworkProtocol.V3.Protocol), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.ServiceMeshMetric), global::SkyWalking.NetworkProtocol.V3.ServiceMeshMetric.Parser, new[]{ "StartTime", "EndTime", "SourceServiceName", "SourceServiceInstance", "DestServiceName", "DestServiceInstance", "Endpoint", "Latency", "ResponseCode", "Status", "Protocol", "DetectPoint" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkyWalking.NetworkProtocol.V3.MeshProbeDownstream), global::SkyWalking.NetworkProtocol.V3.MeshProbeDownstream.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Protocol {
    [pbr::OriginalName("HTTP")] Http = 0,
    [pbr::OriginalName("gRPC")] GRpc = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ServiceMeshMetric : pb::IMessage<ServiceMeshMetric> {
    private static readonly pb::MessageParser<ServiceMeshMetric> _parser = new pb::MessageParser<ServiceMeshMetric>(() => new ServiceMeshMetric());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServiceMeshMetric> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.ServiceMeshReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServiceMeshMetric() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServiceMeshMetric(ServiceMeshMetric other) : this() {
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      sourceServiceName_ = other.sourceServiceName_;
      sourceServiceInstance_ = other.sourceServiceInstance_;
      destServiceName_ = other.destServiceName_;
      destServiceInstance_ = other.destServiceInstance_;
      endpoint_ = other.endpoint_;
      latency_ = other.latency_;
      responseCode_ = other.responseCode_;
      status_ = other.status_;
      protocol_ = other.protocol_;
      detectPoint_ = other.detectPoint_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServiceMeshMetric Clone() {
      return new ServiceMeshMetric(this);
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 1;
    private long startTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 2;
    private long endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "sourceServiceName" field.</summary>
    public const int SourceServiceNameFieldNumber = 3;
    private string sourceServiceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SourceServiceName {
      get { return sourceServiceName_; }
      set {
        sourceServiceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sourceServiceInstance" field.</summary>
    public const int SourceServiceInstanceFieldNumber = 4;
    private string sourceServiceInstance_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SourceServiceInstance {
      get { return sourceServiceInstance_; }
      set {
        sourceServiceInstance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "destServiceName" field.</summary>
    public const int DestServiceNameFieldNumber = 5;
    private string destServiceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DestServiceName {
      get { return destServiceName_; }
      set {
        destServiceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "destServiceInstance" field.</summary>
    public const int DestServiceInstanceFieldNumber = 6;
    private string destServiceInstance_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DestServiceInstance {
      get { return destServiceInstance_; }
      set {
        destServiceInstance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endpoint" field.</summary>
    public const int EndpointFieldNumber = 7;
    private string endpoint_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Endpoint {
      get { return endpoint_; }
      set {
        endpoint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "latency" field.</summary>
    public const int LatencyFieldNumber = 8;
    private int latency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Latency {
      get { return latency_; }
      set {
        latency_ = value;
      }
    }

    /// <summary>Field number for the "responseCode" field.</summary>
    public const int ResponseCodeFieldNumber = 9;
    private int responseCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 10;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "protocol" field.</summary>
    public const int ProtocolFieldNumber = 11;
    private global::SkyWalking.NetworkProtocol.V3.Protocol protocol_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.Protocol Protocol {
      get { return protocol_; }
      set {
        protocol_ = value;
      }
    }

    /// <summary>Field number for the "detectPoint" field.</summary>
    public const int DetectPointFieldNumber = 12;
    private global::SkyWalking.NetworkProtocol.V3.DetectPoint detectPoint_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SkyWalking.NetworkProtocol.V3.DetectPoint DetectPoint {
      get { return detectPoint_; }
      set {
        detectPoint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServiceMeshMetric);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServiceMeshMetric other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (SourceServiceName != other.SourceServiceName) return false;
      if (SourceServiceInstance != other.SourceServiceInstance) return false;
      if (DestServiceName != other.DestServiceName) return false;
      if (DestServiceInstance != other.DestServiceInstance) return false;
      if (Endpoint != other.Endpoint) return false;
      if (Latency != other.Latency) return false;
      if (ResponseCode != other.ResponseCode) return false;
      if (Status != other.Status) return false;
      if (Protocol != other.Protocol) return false;
      if (DetectPoint != other.DetectPoint) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StartTime != 0L) hash ^= StartTime.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      if (SourceServiceName.Length != 0) hash ^= SourceServiceName.GetHashCode();
      if (SourceServiceInstance.Length != 0) hash ^= SourceServiceInstance.GetHashCode();
      if (DestServiceName.Length != 0) hash ^= DestServiceName.GetHashCode();
      if (DestServiceInstance.Length != 0) hash ^= DestServiceInstance.GetHashCode();
      if (Endpoint.Length != 0) hash ^= Endpoint.GetHashCode();
      if (Latency != 0) hash ^= Latency.GetHashCode();
      if (ResponseCode != 0) hash ^= ResponseCode.GetHashCode();
      if (Status != false) hash ^= Status.GetHashCode();
      if (Protocol != 0) hash ^= Protocol.GetHashCode();
      if (DetectPoint != 0) hash ^= DetectPoint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StartTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StartTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(EndTime);
      }
      if (SourceServiceName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SourceServiceName);
      }
      if (SourceServiceInstance.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SourceServiceInstance);
      }
      if (DestServiceName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DestServiceName);
      }
      if (DestServiceInstance.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DestServiceInstance);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Endpoint);
      }
      if (Latency != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Latency);
      }
      if (ResponseCode != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ResponseCode);
      }
      if (Status != false) {
        output.WriteRawTag(80);
        output.WriteBool(Status);
      }
      if (Protocol != 0) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Protocol);
      }
      if (DetectPoint != 0) {
        output.WriteRawTag(96);
        output.WriteEnum((int) DetectPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StartTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTime);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      if (SourceServiceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SourceServiceName);
      }
      if (SourceServiceInstance.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SourceServiceInstance);
      }
      if (DestServiceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DestServiceName);
      }
      if (DestServiceInstance.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DestServiceInstance);
      }
      if (Endpoint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Endpoint);
      }
      if (Latency != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Latency);
      }
      if (ResponseCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResponseCode);
      }
      if (Status != false) {
        size += 1 + 1;
      }
      if (Protocol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Protocol);
      }
      if (DetectPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DetectPoint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServiceMeshMetric other) {
      if (other == null) {
        return;
      }
      if (other.StartTime != 0L) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      if (other.SourceServiceName.Length != 0) {
        SourceServiceName = other.SourceServiceName;
      }
      if (other.SourceServiceInstance.Length != 0) {
        SourceServiceInstance = other.SourceServiceInstance;
      }
      if (other.DestServiceName.Length != 0) {
        DestServiceName = other.DestServiceName;
      }
      if (other.DestServiceInstance.Length != 0) {
        DestServiceInstance = other.DestServiceInstance;
      }
      if (other.Endpoint.Length != 0) {
        Endpoint = other.Endpoint;
      }
      if (other.Latency != 0) {
        Latency = other.Latency;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.Protocol != 0) {
        Protocol = other.Protocol;
      }
      if (other.DetectPoint != 0) {
        DetectPoint = other.DetectPoint;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartTime = input.ReadInt64();
            break;
          }
          case 16: {
            EndTime = input.ReadInt64();
            break;
          }
          case 26: {
            SourceServiceName = input.ReadString();
            break;
          }
          case 34: {
            SourceServiceInstance = input.ReadString();
            break;
          }
          case 42: {
            DestServiceName = input.ReadString();
            break;
          }
          case 50: {
            DestServiceInstance = input.ReadString();
            break;
          }
          case 58: {
            Endpoint = input.ReadString();
            break;
          }
          case 64: {
            Latency = input.ReadInt32();
            break;
          }
          case 72: {
            ResponseCode = input.ReadInt32();
            break;
          }
          case 80: {
            Status = input.ReadBool();
            break;
          }
          case 88: {
            Protocol = (global::SkyWalking.NetworkProtocol.V3.Protocol) input.ReadEnum();
            break;
          }
          case 96: {
            DetectPoint = (global::SkyWalking.NetworkProtocol.V3.DetectPoint) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MeshProbeDownstream : pb::IMessage<MeshProbeDownstream> {
    private static readonly pb::MessageParser<MeshProbeDownstream> _parser = new pb::MessageParser<MeshProbeDownstream>(() => new MeshProbeDownstream());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MeshProbeDownstream> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkyWalking.NetworkProtocol.V3.ServiceMeshReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MeshProbeDownstream() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MeshProbeDownstream(MeshProbeDownstream other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MeshProbeDownstream Clone() {
      return new MeshProbeDownstream(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MeshProbeDownstream);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MeshProbeDownstream other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MeshProbeDownstream other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
